---
# use latest version of git
- name: Add git ppa.
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:git-core/ppa"
    state: present

- name: Create apt keyring directory.
  become: true
  ansible.builtin.file:
    mode: "0755"
    path: /etc/apt/keyrings
    state: directory

- name: Add apt repository for GitHub CLI.
  block:
    - name: Add GitHub CLI keyring.
      become: true
      ansible.builtin.get_url:
        dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
        mode: "0644"
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg

    - name: Add GitHub CLI repo.
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present

- name: Install packages through apt.
  become: true
  ansible.builtin.apt:
    cache_valid_time: 86_400  # one day
    update_cache: true
    name:
      - code
      - fzf
      - gh  # github cli
      - google-chrome-stable
      - htop
      - keepassxc
      - python3-psutil  # requirement for ansible dconf module
      - tmux
      - vlc
    state: present

- name: Include variables for gnome configuration through dconf.
  ansible.builtin.include_vars: dconf.yml
  tags: ["gnome"]

- name: Configure gnome to be cooler, more like a dwarf.
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ dconf_settings | dict2items }}"
  tags: ["gnome"]
