---
- name: Setup my dev machine.
  hosts: all

  pre_tasks:
    - name: Install dependencies from galaxy.
      ansible.builtin.command: ansible-galaxy install -r requirements.yml
      tags: ["all", "galaxy"]

  roles:
    - role: me
      tags: ["all"]

    - role: geerlingguy.docker
      become: true
      vars:
        docker_edition: 'ce'
        docker_install_compose: true
        docker_install_compose_plugin: false
        docker_service_manage: "MOLECULE_FILE in lookup('env')"
      when: ansible_distribution != 'MacOSX'
      tags: ["all", "docker"]

  tasks:
    - name: Add git configuration.
      ansible.builtin.template:
        src: templates/.gitconfig
        backup: true
        dest: "{{ ansible_user_dir }}/.gitconfig"
        mode: "0644"
      tags: ["all", "dotfiles"]
