---
- name: Setup ssh.
  ansible.builtin.import_tasks: ssh.yml
  tags: ["ssh"]

- name: Setup MacOS specific configuration.
  ansible.builtin.import_tasks: extra_MacOSX.yml
  when: ansible_distribution == 'MacOSX'
  tags: ["mac", "packages"]

- name: Setup Pop! OS specific configuration.
  ansible.builtin.import_tasks: extra_Archlinux.yml
  when: ansible_distribution == 'Archlinux'
  tags: ["arch"]

- name: Use the fish shell.
  ansible.builtin.import_tasks: fish.yml
  tags: ["fish"]

- name: Install & build neovim from source.
  ansible.builtin.import_tasks: neovim.yml
  tags: ["neovim"]
