---
dconf_settings:
  /org/gnome/desktop/interface/clock-format: "'24h'"
  /org/gnome/desktop/interface/color-scheme: "'prefer-dark'"
  /org/gnome/desktop/interface/enable-animations: "false"
  /org/gnome/desktop/interface/show-battery-percentage: "true"
  /org/gnome/desktop/peripherals/touchpad/natural-scroll: "true"
  /org/gnome/desktop/peripherals/touchpad/speed: "0.31"
  /org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled: "true"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-1: "['<Shift><Super>Home', '<Primary><Shift>exclam']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-2: "['<Primary><Shift>at']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-3: "['<Primary><Shift>numbersign']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-4: "['<Primary><Shift>dollar']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-5: "['<Primary><Shift>percent']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-6: "['<Primary><Shift>dead_circumflex']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-7: "['<Primary><Shift>ampersand']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-8: "['<Primary><Shift>asterisk']"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-9: "['<Primary><Shift>parenleft']"
  /org/gnome/desktop/wm/keybindings/switch-input-source: "@as []"
  /org/gnome/desktop/wm/keybindings/switch-input-source-backward: "@as []"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-1: "['<Primary>1']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-2: "['<Primary>2']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-3: "['<Primary>3']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-4: "['<Primary>4']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-5: "['<Primary>5']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-6: "['<Primary>6']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-7: "['<Primary>7']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-8: "['<Primary>8']"
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-9: "['<Primary>9']"
  /org/gnome/desktop/wm/preferences/button-layout: "'appmenu:minimize,close'"
  /org/gnome/desktop/wm/preferences/num-workspaces: "9"
  /org/gnome/mutter/dynamic-workspaces: "false"
  /org/gnome/mutter/edge-tiling: "false"
  /org/gnome/mutter/overlay-key: "''"
  /org/gnome/shell/disabled-extensions: "['popx11gestures@system76.com']"
  /org/gnome/shell/extensions/dash-to-dock/extend-height: "false"
  /org/gnome/shell/extensions/dash-to-dock/manualhide: "true"
  /org/gnome/shell/extensions/pop-cosmic/clock-alignment: "'RIGHT'"
  /org/gnome/shell/extensions/pop-cosmic/show-applications-button: "false"
  /org/gnome/shell/extensions/pop-shell/activate-launcher: "['<Super>space']"
  /org/gnome/shell/extensions/pop-shell/gap-inner: "uint32 0"
  /org/gnome/shell/extensions/pop-shell/gap-outer: "uint32 0"
  /org/gnome/shell/extensions/pop-shell/show-title: "true"
  /org/gnome/shell/extensions/pop-shell/snap-to-grid: "false"
  /org/gnome/shell/extensions/pop-shell/tile-by-default: "true"
  /org/gtk/settings/file-chooser/clock-format: "'24h'"
  /system/locale/region: "'de_DE.UTF-8'"
