---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    dockerfile: Dockerfile.j2
    image: hugojosefson/popos
    platform: linux/amd64
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
verifier:
  name: ansible
