---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: archlinux:base-devel
    platform: linux/amd64
    pre_build_image: false
provisioner:
  name: ansible
  options:
    skip-tags: "galaxy, ssh, neovim"
  env:
    ANSIBLE_ROLES_PATH: "../../.galaxy:../../roles"
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
verifier:
  name: ansible
