#!/bin/sh

set -u

if ! [ -f ".gitignore" ]; then
	echo "Not in project root."
	exit 1
fi

yamllint -d relaxed main.yml roles
ansible-lint --exclude .galaxy

if [ "${1:-}" = "--full" ]; then
	molecule test
fi
