#!/bin/sh

set -u

if [ "$(basename $PWD)" != "ansible" ]; then
	echo "Not in project root."
	exit 1
fi

yamllint -d relaxed .
ansible-lint --exclude ".galaxy/"

if [ "${1:-}" = "--full" ]; then
    ANSIBLE_VAULT_PASSWORD_FILE="~/.vault_key" molecule test --skip-tags=dconf
fi
