return {
	"folke/trouble.nvim",
	cmd = "TroubleToggle",
	keys = {
		{
			"<leader>xq",
			"<cmd>Trouble qflist toggle<cr>",
			desc = "Trouble: toggle [q]uickfix",
			silent = true,
			noremap = true,
		},
		{
			"<leader>xw",
			"<cmd>Trouble diagnostics toggle<cr>",
			desc = "Trouble: toggle [w]orkspace diagnostics",
			silent = true,
			noremap = true,
		},
	},
	opts = {
		icons = {
			folder_closed = ">", -- icon used for closed folds
			folder_open = "v", -- icon used for open folds
			Array = "",
			Boolean = "",
			Class = "",
			Constant = "",
			Constructor = "",
			Enum = "",
			EnumMember = "",
			Event = "",
			Field = "",
			File = "",
			Function = "",
			Interface = "",
			Key = "",
			Method = "",
			Module = "",
			Namespace = "",
			Null = "",
			Number = "",
			Object = "",
			Operator = "",
			Package = "",
			Property = "",
			String = "",
			Struct = "",
			TypeParameter = "",
			Variable = "",
		},
	},
}
